stages:
  data-split:
    cmd: python3 src/data_split.py
    deps:
    - data/raw_data/clean_data.csv
    - src/data_split.py
    outs:
    - data/processed_data/x_test.npy
    - data/processed_data/x_train.npy
    - data/processed_data/y_test.npy
    - data/processed_data/y_train.npy
  normalize:
    cmd: python3 src/normalize.py
    deps:
      - data/processed_data/x_train.npy
      - data/processed_data/x_test.npy
      - src/normalize.py
    outs:
      - data/scaling_model.pkl
  training:
    cmd: python3 src/training.py
    deps:
      - data/processed_data/x_train.npy
      - data/processed_data/y_train.npy
      - data/scaling_model.pkl
      - src/training.py
    outs:
      - data/gbrt_model.pkl
