name: Continuous Machine learning

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          pip install -r requirements.txt

          # Pull latest data from remote
          dvc pull -r mlops-org

          # Reproduce pipeline if any changes detected in dependencies
          dvc repro
          
          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
          
          # Add figure to report
          cml-publish deviance.png --md >> report1.md
          cml-publish feature_importance.png --md >> report2.md
          cml-publish learning_curve.png --md >> report3.md

          cml-send-comment report1.md
          cml-send-comment report2.md
          cml-send-comment report3.md

